http/main/default/objects/Address_Change_Event__e/Address_Change_Event__e.object-meta.xml
<CustomObject>
    <description>Simple platform event to capture an Address for the purposes of test project</description>
    <label>Address Change Event</label>
    <pluralLabel>Address Change Events</pluralLabel>
</CustomObject>

src/http/main/default/objects/Address_Change_Event__e/fields/ObjectId__c.field-meta.xml
<CustomField>
    <fullName>ObjectId__c</fullName>
    <label>Object Id</label>
    <required>true</required>
    <type>Text</type>
    <length>18</length>
</CustomField>

src/http/main/default/classes/AddressChangeEventTriggerHandler.cls
public class AddressChangeEventTriggerHandler {
    public static final string NAMED_CREDENTIAL = 'AddressRestService';
    
    public static void afterInsert(List<Address_Change_Event__e> allEvents) {
        if(allEvents.isEmpty()) {
            return;
        }
        
        for (Address_Change_Event__e evt : allEvents) {
            //string namedCredential = 'AddressRestService';
            string namedCredential = NAMED_CREDENTIAL;
            string endpoint = String.format('callout:{0}/{1}', new String[] { namedCredential, evt.ObjectId__c });
            AddressDto dto = new AddressDto(evt);
            
            System.debug(LOGGINGLEVEL.DEBUG, string.format('Publishing event for [{0}] to [{1}]', new String[] { evt.ObjectId__c, endpoint }));
            
            new HttpFutureCallout()
		        .setMethod('POST')
                .setEndpoint(endpoint)
        		.setHeader('Content-Type', 'text/plain')
        		.setBody(JSON.serialize(dto))
                .send();

            EventBus.TriggerContext.currentContext().setResumeCheckpoint(evt.ReplayId);
            if (Limits.getFutureCalls() >= Limits.getLimitFutureCalls()) {
                break;
            }            
        }
    }
}