http/main/default/objects/Address_Change_Event__e/Address_Change_Event__e.object-meta.xml
<CustomObject>
    <description>Simple platform event to capture an Address for the purposes of test project</description>
    <label>Address Change Event</label>
    <pluralLabel>Address Change Events</pluralLabel>
</CustomObject>

src/demo-http/main/default/objects/Address_Change_Event__e/fields/AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>AddressLine1__c</fullName>
    <description>Address Line 1</description>
    <label>AddressLine1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/demo-http/main/default/objects/Address_Change_Event__e/fields/AddressLine2__c.field-meta.xml
<CustomField>
    <fullName>AddressLine2__c</fullName>
    <description>Address Line 2</description>
    <label>AddressLine2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

http/main/default/objects/Address_Change_Event__e/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>County</description>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/demo-http/main/default/objects/Address_Change_Event__e/fields/HouseNumberOrName__c.field-meta.xml
<CustomField>
    <fullName>HouseNumberOrName__c</fullName>
    <description>House Number or Name</description>
    <label>HouseNumberOrName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/http/main/default/objects/Address_Change_Event__e/fields/ObjectId__c.field-meta.xml
<CustomField>
    <fullName>ObjectId__c</fullName>
    <label>Object Id</label>
    <required>true</required>
    <type>Text</type>
    <length>18</length>
</CustomField>

http/main/default/objects/Address_Change_Event__e/fields/PostCode__c.field-meta.xml
<CustomField>
    <fullName>PostCode__c</fullName>
    <description>UK post code</description>
    <label>PostCode</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

http/main/default/objects/Address_Change_Event__e/fields/TownOrCity__c.field-meta.xml
<CustomField>
    <fullName>TownOrCity__c</fullName>
    <description>Town or City</description>
    <label>TownOrCity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

http/main/default/classes/AddressDto.cls
public with sharing class AddressDto {
    public string ObjectId;
    public string HouseNumberOrName;
    public string AddressLine1;
    public string AddressLine2;
    public string TownOrCity;
    public string County;
    public string PostCode;

    public AddressDto(Address_Change_Event__e evt) {
        ObjectId = evt.ObjectId__c;
        HouseNumberOrName = evt.HouseNumberOrName__c;
        AddressLine1 = evt.AddressLine1__c;
        AddressLine2 = evt.AddressLine2__c;
        TownOrCity = evt.TownOrCity__c;
        County = evt.County__c;
        PostCode = evt.PostCode__c;
    }
}