http/main/default/objects/Address_Change_Event__e/Address_Change_Event__e.object-meta.xml
<CustomObject>
    <description>Simple platform event to capture an Address for the purposes of test project</description>
    <label>Address Change Event</label>
    <pluralLabel>Address Change Events</pluralLabel>
</CustomObject>

src/demo-http/main/default/objects/Address_Change_Event__e/fields/AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>AddressLine1__c</fullName>
    <description>Address Line 1</description>
    <label>AddressLine1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/demo-http/main/default/objects/Address_Change_Event__e/fields/HouseNumberOrName__c.field-meta.xml
<CustomField>
    <fullName>HouseNumberOrName__c</fullName>
    <description>House Number or Name</description>
    <label>HouseNumberOrName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/http/main/default/objects/Address_Change_Event__e/fields/ObjectId__c.field-meta.xml
<CustomField>
    <fullName>ObjectId__c</fullName>
    <label>Object Id</label>
    <required>true</required>
    <type>Text</type>
    <length>18</length>
</CustomField>

http/main/default/objects/Address_Change_Event__e/fields/PostCode__c.field-meta.xml
<CustomField>
    <fullName>PostCode__c</fullName>
    <description>UK post code</description>
    <label>PostCode</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

http/main/default/objects/Address_Change_Event__e/fields/TownOrCity__c.field-meta.xml
<CustomField>
    <fullName>TownOrCity__c</fullName>
    <description>Town or City</description>
    <label>TownOrCity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/demo-http/main/default/classes/AddressChangeEventTriggerHandlerTest.cls
@IsTest
public class AddressChangeEventTriggerHandlerTest {

    @IsTest 
    public static void Given_AddressEventRaised_When_TriggerIsHandled_Then_NewAddressIsPublishedToRestService() {
        Address_Change_Event__e evt = createAddressChangedPlatformEvent();
        AddressDto dto = new AddressDto(evt);
        String endpoint = String.format('callout:{0}/{1}', new String[] { AddressChangeEventTriggerHandler.NAMED_CREDENTIAL, evt.ObjectId__c });
        
    	HttpRequest expectedRequest = new HttpRequest();
        expectedRequest.setMethod('POST');
		expectedRequest.setHeader('Content-Type', 'text/plain');
        expectedRequest.setEndpoint(endpoint);
        expectedRequest.setBody(JSON.serialize(dto));
        MockHttpCalloutQueue mockCallout = new MockHttpCalloutQueue().expect(expectedRequest, httpResponseCreated());
        Test.setMock(HttpCalloutMock.class, mockCallout);
        
        Test.startTest();
        EventBus.publish(evt);
        Test.getEventBus().deliver();
        Test.stopTest();
        
        System.assertEquals(true, mockCallout.verifyExpectations(), 'Mock callout cannot verify the correct calls were made');
    }

    @IsTest
    public static void Given_AddressChangePlatformEvent_When_Configured_Then_Subscribed() {
        List<EventBusSubscriber> subscriber = [SELECT Name, Position, Retries, LastError FROM EventBusSubscriber WHERE Topic='Address_Change_Event__e' AND Name = 'AddressChangeEventTrigger' LIMIT 1];
        System.assertEquals(1, subscriber.size(), 'AddressChangeEventTrigger is not subscribed to the Address_Change_Event__e Platform event');
    }

    private static Address_Change_Event__e createAddressChangedPlatformEvent() {
        return new Address_Change_Event__e(
            ObjectId__c = '123456789',
            HouseNumberOrName__c = '22',
            AddressLine1__c = 'Acacia Avenue',
            TownOrCity__c = 'Littlehampton',
            PostCode__c = 'BAN ANA'
        );
    }

    private static HttpResponse httpResponseCreated() {
        HttpResponse response = new HttpResponse();
        response.setStatusCode(201);
        return response;
    }
}